version: "3.8"
services:
  llm:
    build: ./app
    container_name: fitmind_llm
    env_file: ./app/.env
    restart: always
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    container_name: fitmind_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    restart: always
