networks:
  nutrion_net:
    driver: bridge

services:
  llm:
    build: ./app
    container_name: nutrion_llm
    env_file: ./app/.env
    restart: always
    ports:
      - "8000:8000"
    networks:
      - nutrion_net

  nginx:
    image: nginx:latest
    container_name: nutrion_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - nutrion_net
