services:
  llm:
    build: ./app
    container_name: nutrion_llm
    restart: always
    env_file:
      - ../.env
    networks:
      - nutrion_net
    ports:
      - "8001:8000"

  nginx:
    image: nginx:latest
    container_name: nutrion_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - nutrion_net
  
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    ports:
      - 8008:8008
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nutrion_net

networks:
  nutrion_net:
    driver: bridge
