services:
  ollama:
    image: ollama/ollama:latest
    container_name: nutrion_ollama
    restart: always
    networks:
      - nutrion_net
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
  
  llm:
    build: ./app
    container_name: nutrion_llm
    restart: always
    env_file:
      - ../.env
    networks:
      - nutrion_net
    ports:
      - "8013:8013"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434

  nginx:
    image: nginx:latest
    container_name: nutrion_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - nutrion_net
  
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    ports:
      - 8008:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nutrion_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  nutrion_net:
    driver: bridge

volumes:
  ollama_data: