services:
  bot:
    build: ./app
    container_name: nutrion_bot
    restart: always
    env_file:
      - ../.env
    ports:
      - "8069:8000"
    networks:
      - nutrion_net
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app

  db:
    image: postgres:17
    container_name: nutrion_bot_db
    restart: always
    env_file:
      - ../.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nutrion_net
  
  ollama:
    image: ollama/ollama:latest
    container_name: nutrion_ollama
    restart: always
    networks:
      - nutrion_net
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0

  llm:
    build: ../llm/app
    container_name: nutrion_llm
    restart: always
    env_file:
      - ../.env
    networks:
      - nutrion_net
    ports:
      - "8013:8013"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    ports:
      - 8008:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nutrion_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  redis:
    image: redis:7-alpine
    container_name: nutrion_redis
    restart: always
    volumes:
      - redisdata:/var/lib/redis/data
    networks:
      - nutrion_net

networks:
  nutrion_net:
    driver: bridge

volumes:
  pgdata:
  redisdata:
  ollama_data:
