services:
  bot:
    build: ./app
    container_name: nutrion_bot
    restart: always
    env_file:
      - ../.env
    ports:
      - "8069:8000"
    networks:
      - nutrion_net
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app

  db:
    image: postgres:17
    container_name: nutrion_bot_db
    restart: always
    env_file:
      - ../.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nutrion_net
  
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - 8008:8008
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nutrion_net

networks:
  nutrion_net:
    driver: bridge

volumes:
  pgdata:
