version: "3.8"

services:
  bot:
    build: ./app
    env_file: ./app/.env
    restart: always
    ports:
      - "8069:8000"
    networks:
      - nutrion_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=Europe/Moscow

networks:
  nutrion_net:
    driver: bridge
